project_id = "szkpdiuzazccnhilksvo"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.ai-generate]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.create-image-payment]
verify_jwt = false

[functions.verify-image-payment]
verify_jwt = false

[functions.generate-project-image]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false

[functions.check-subtitle-usage]
verify_jwt = false
